/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData ce = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData turtoise = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData hare = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData weee = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData mobware = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData carousel_view = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData texture_wood_alt = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData color_palette_alt = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData image = const IconData(0xe80a, fontFamily: _kFontFam);
}
