/// Flutter icons custom_icons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  custom_icons
///      fonts:
///       - asset: fonts/custom_icons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'custom_icons';

  static const IconData ce = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData turtoise =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData hare = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData weee = const IconData(0xe803, fontFamily: _kFontFam);
}
